export const COMPANY = {
  name: 'Finriseo',
  legalName: 'UpAndAlone Fintech Pvt. Ltd.',
  tagline: 'Compare. Apply. Get Loan.',
  description: "India's trusted loan comparison platform.",
  cin: 'U74999MH2024PTC000000',
  dsaRegistration: 'DSA/MH/2024/001234',
  email: 'support@finriseo.com',
  legalEmail: 'legal@finriseo.com',
  dpoEmail: 'dpo@finriseo.com',
  grievanceEmail: 'grievance@finriseo.com',
  phone: '1800-123-456',
  phoneHref: 'tel:+911800123456',
  workingHours: 'Monday - Saturday, 9:00 AM - 7:00 PM IST',
  address: {
    line1: '301, FinServe Tower, BKC',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    country: 'India',
    get full() { return `${this.line1}, ${this.city}, ${this.state} - ${this.pincode}`; },
  },
  grievanceOfficer: {
    name: 'Rajesh Mehta',
    email: 'grievance@finriseo.com',
    phone: '+91-22-4000-1234',
  },
  social: {
    linkedin: 'https://linkedin.com/company/finriseo',
    twitter: 'https://twitter.com/finriseo',
    website: 'https://finriseo.com',
  },
  stats: {
    customers: '2,00,000+',
    customersShort: '2L+',
    disbursed: '₹500 Cr+',
    partners: '50+',
    rating: '4.8',
  },
} as const;
